and the rule is proved that

\[\frac{du^{*}}{dx}=nw^{*-1}\frac{du}{dx},\]

where \(n\) is a positive fraction whose numerator and denominator are integers. This rule has already been used in the solution of numerous exercises.

## 34 The Derivative of a Constant

Let \(y=c\), where \(c\) is a constant. Corresponding to any \(\Delta x,\Delta y=0\), and consequently

\[\frac{\Delta y}{\Delta x}=0,\]

and

\[\lim\limits_{\Delta x\to 0}\frac{\Delta y}{\Delta x}=0,\]

or

\[\frac{dy}{dx}=0.\]

The derivative of a constant is zero.

Interpret this result geometrically.

## 35 The Derivative of the Sum of Two Functions

Let

\[y=u+v,\]

where \(u\) and \(v\)are functions of \(x\).Let \(\Delta u\), \(\Delta v\), and \(\Delta y\) be the increments of \(u,v\), and \(y\), respectively, corresponding to the increment \(\Delta x\).

\[y+\Delta y =u+\Delta u+v+\Delta v\] \[\Delta y =\Delta u+\Delta v\] \[\frac{\Delta y}{\Delta x} =\frac{\Delta u}{\Delta x}+\frac{\Delta v}{\Delta x}\] \[\frac{dy}{\bar{dx}} =\frac{du}{dx}+\frac{dv}{dx},\]

or

\[\frac{d(u+v)}{dx}=\frac{du}{dx}+\frac{dv}{dx}.\]

The derivative of the sum of two functions is equal to the sum of their derivatives.

