equation (1). To begin with, under our experimental conditions \(\nu_{4}\) is generally small in comparison with the other \(\nu\prime\prime\)s and can be neglected for purposes of a qualitative discussion. Secondly, \(\lambda\) turns out to be a small positive root - of the order of the smaller \(\nu\) values and small compared with the larger \(\nu\) values. Thus, we neglect \(\lambda^{3}\) in comparison with the other terms and rewrite equation (1):

\[\left[ {\left( {\nu_{1} + \nu_{5}} \right) + \nu_{2} + \nu_{3}} \right\rbrack\lambda^{2} + \nu_{3}{\left( {\nu_{1} + \nu_{5}} \right)}\lambda \cong 2\nu_{2}\nu_{3}{\left( {\nu_{1} + \nu_{5}} \right)}\]

If the amount of hydrogen in a mixture is large in comparison to oxygen, \(\nu_{1}\) and \(\nu_{3}\) are large and the term involving \(\lambda^{2}\) may be neglected; in this event,

\[\lambda \cong 2\nu_{2}\]

On the other hand, if only a trace of hydrogen is present, \(\nu_{3}\) is small, the term involving \(\lambda\) may be neglected, and

\[\lambda^{2} \simeq \frac{2\nu_{2}\nu_{3}{\left( {\nu_{1} + \nu_{5}} \right)}}{\nu_{2} + {\left( {\nu_{1} + \nu_{5}} \right)}}\]

If we choose a mixture with a large amount of carbon monoxide, \(\nu_{5}\) is large and

\[\lambda \sim \sqrt{2\nu_{2}\nu_{3}}\]

Whereas if there is a large amount of oxygen, \(\nu_{2}\) is large and

\[\lambda \sim \sqrt{2\nu_{3}{\left( {\nu_{1} + \nu_{5}} \right)}}\]

\[- \sqrt{2\nu_{3}{\nu_{1}}}\]

\[\left[ {\text{H}_{2}} \right] > \left[ {\text{CO}} \right]\]

\[- \sqrt{2\nu_{3}{\nu_{5}}}\]

\[\left[ {\text{CO}} \right] > \left[ {\text{H}_{2}} \right]\]

This, then, outlines a strategy for obtaining rates of reactions I, II, III, and V. First, a mixture rich in hydrogen is used to determine k2. Next, with k2 known, a mixture with a trace of hydrogen and rich in carbon monoxide is used to deter-mine k3. Finally, with k3 known, mixtures with excess oxygen and varying pro