

### 2.1. Molecules in Cavities

The molecular Hamiltonian describes the vibrational modes as harmonic oscillators which are coupled to each other by a third order anharmonic coupling term. This term is obtained by using a Taylor expansion of the the harmonic potential and therefore includes a mediator for the IVR pathways in the model. So the molecular Hamiltonian for two separate modes (\(q,Q\)) in the molecular part is described by:

\[\hat{H}_{mol}=\hbar\omega_{q}(\hat{b}^{\dagger}\hat{b})+\hbar\omega_{Q}(\hat{c} ^{\dagger}\hat{c})+\sum_{r,s}^{3}\eta_{r,s}^{qQ}\left(\hat{b}^{\dagger}+\hat{b} \right)^{r}\left(\hat{c}^{\dagger}+\hat{c}\right)^{s}. \tag{2.3}\]

Here \(\omega_{q}\) describes the fundamental frequency of the molecular mode \(q\) which is coupled to the cavity and the respective degrees of freedom are expressed with the ladder operators, \(\hat{b}^{\dagger}\) and \(\hat{b}\). In the second part, a lower energy vibrational mode \(Q\) is described with its respective frequency \(\omega_{Q}\) and the corresponding ladder operators \((\hat{c}^{\dagger},\hat{c})\). The last term describes the general form of the third order couplings, where \(\eta_{r,s}\) describes the anharmonic coupling constants and will be referred to by \(\hat{W}\).[4] To obtain the corresponding eigenvector for the upper and lower polariton, the Hamiltonian matrix is diagonalized. By doing this one arrives at the following expression for the polaritons:[22, 25]

\[|\psi_{(UP,LP)};0\rangle=\frac{|1_{c},0,0\rangle\pm|0_{c},1,0\rangle}{\sqrt{2}}. \tag{2.4}\]

Here the uncoupled states are described by the kets where the first term describes the excitation in the cavity state, the second term describes the excitation in the high frequency mode and the last term is the excitation in the \(Q\) mode.

#### 2.1.2. Anharmonic Coupling Terms

Under specific symmetry considerations not all intramolecular coupling orders (\(r,s\)) are relevant. In this specific case only orders with \(r+s\leq 3\) are considered. Since all considered coordinates are intramolecular normal modes the bilinear coupling (\(1,1\)) is in this case equal to zero. Generally, all terms of the potential energy have to transform according to the totally symmetric representation of the molecules point group.[26] Thus according to the following equation:

\[\left(\Gamma^{(q)}\right)^{r}\times\left(\Gamma^{(Q)}\right)^{s}\subset\Gamma_{ A}. \tag{2.5}\]

Since the models discussed in this work modeled after the octahedral W(CO)\({}_{6}\) molecule and thus exhibit non-Abelian point group symmetry, the various possible couplings have